# Generated by Django 5.0.8 on 2024-08-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_cashflow_beginning_cash_position_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='company_ask',
            new_name='CompanyAsk',
        ),
    ]
